# Generated by Django 5.2 on 2025-04-12 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ULASActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Case Supervision', 'Case Supervision'), ('Client Consultation', 'Client Consultation'), ('Legal Research', 'Legal Research'), ('Drafting of Pleadings or affidavits', 'Drafting of Pleadings or affidavits'), ('Court Appearances', 'Court Appearances'), ('Mediation or ADR Facilitation', 'Mediation or ADR Facilitation'), ('Training or Lectures for Law Interns', 'Training or Lectures for Law Interns'), ('Community Legal Education', 'Community Legal Education'), ('Other', 'Other')], max_length=255)),
                ('description', models.TextField()),
                ('students_supervised', models.PositiveIntegerField(blank=True, null=True)),
                ('clients_served', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_activity', models.DateField()),
                ('hours_rendered', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
