# Generated by Django 5.1.6 on 2025-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Case Supervision', 'Case Supervision'), ('Client Consultation', 'Client Consultation'), ('Legal Research', 'Legal Research'), ('Drafting of Pleadings or affidavits', 'Drafting of Pleadings or affidavits'), ('Court Appearances', 'Court Appearances'), ('Mediation or ADR Facilitation', 'Mediation or ADR Facilitation'), ('Training or Lectures for Law Interns', 'Training or Lectures for Law Interns'), ('Community Legal Education', 'Community Legal Education'), ('Other', 'Other (Please specify)')], max_length=100)),
                ('description', models.TextField()),
                ('num_students', models.PositiveIntegerField(blank=True, null=True)),
                ('num_clients', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hours_rendered', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proof', models.ImageField(upload_to='proofs/')),
            ],
        ),
    ]
