# Generated by Django 5.1.6 on 2025-04-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='num_clients',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='num_students',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='number_of_clients',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='number_of_students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
