# Generated by Django 5.1.6 on 2025-04-13 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0003_remove_activity_activity_remove_activity_num_clients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('year_admitted', models.CharField(max_length=10)),
                ('office_name', models.CharField(blank=True, max_length=100)),
                ('law_school', models.CharField(max_length=100)),
                ('work_cell', models.CharField(blank=True, max_length=20)),
                ('roll_number', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('office_address', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
