# Generated by Django 5.2 on 2025-05-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0005_activity_user_alter_activity_activity_type_and_more'),
        ('XUCLA', '0007_activity_user_alter_activity_number_of_clients_and_more'),
    ]

    operations = [
    ]
