# Generated by Django 5.2 on 2025-05-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0008_merge_20250518_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number_of_clients',
            field=models.PositiveIntegerField(default=0, help_text='Number of Clients served'),
        ),
    ]
