# Generated by Django 5.1.6 on 2025-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0011_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
