# Generated by Django 5.2.1 on 2025-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XUCLA', '0012_alter_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number_of_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
